apiVersion: v1
kind: Service
metadata:
  name: mapdemo-service
  namespace: gis
  labels:
    app: mapdemo
spec:
  ports:
  - port: 3000
    name: http
  type: LoadBalancer
  selector:
    app: mapdemo
